### ISSUE TITLE
gRPC doc 

### ISSUE THREAD

**Issue by innerop** [bayard-search/bayard#70]
Hi,

I’ve not used gRPC before but I’d like to give it a shot. As far as docs go, where do I look for any info regarding setting up gPRC calls to the Bayard API?

Cheers

**Comment by mosuka** [comment]
Hi @innerop ,
Thanks for your interest.
I'll split the gRPC client to other repository in the future. I'll be preparing documentation at that time, so please wait a little longer.
Until then, it's easier to get access through an HTTP gateway.

**Comment by innerop** [comment]
Ok. Sounds great. Thank you.
