### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by innerop** [bayard-search/bayard#71]
Hi,

In a cluster scenario, do the HTTP Gateway or gRPC run on all modes or only on the master node? 

Would be cool to have a slack channel or I can combine all my questions into one thread. 

Bayard looks good. 

Thanks

**Comment by mosuka** [comment]
Hi @innerop ,
The HTTP gateway starts as a separate process.
If you have already started a three-node cluster of 127.0.0.1:5001,127.0.0.1:5002,127.0.0.1:5003, start the HTTP gateway as follows and the HTTP gateway provides round-robin the three nodes.

```
$ ./bin/bayard gateway --servers=127.0.0.1:5001,127.0.0.1:5002,127.0.0.1:5003
```

Also, we have a Gitter Chat. Please see the following:
https://gitter.im/bayard-search/bayard

**Comment by innerop** [comment]
Ok. I posted a follow up question on Gitter.
