### ISSUE TITLE
client endpoint access

### ISSUE THREAD

**Issue by pmirla** [bayard-search/bayard#9]
I was able to get server running thanks for clear instructions.
Once the server is running, how do I query from a webpage ? 
I am new to gRPC, hence I am looking for suggestions on how to query and consume results.
Thank you - Bayard team

**Comment by mosuka** [comment]
@pmirla 
Thank you for your inquiry.
Refer to this code if your application is written in Rust.
When connecting directly from other languages ​​using gRPC, you will need to generate code for each language, but these codes are not currently ready. You can also generate code for the language you are using by yourself, please see the gRPC documentation.
Also, I'm planning to add a REST API layer in the near future.

**Comment by pmirla** [comment]
Thanks very much for your response @mosuka 
I will look forward to REST API

**Comment by mosuka** [comment]
Hi @pmirla ,
Bayard v0.2.0 has been released. REST API to access the gRPC server that provides index is available.

**Comment by pmirla** [comment]
Thank you for the note Minoru. I will check it out
